/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesMovieIdRouteImport } from './routes/movies.$movieId'
import { Route as MoviesMovieIdSeatsRouteImport } from './routes/movies.$movieId_.seats'
import { Route as MoviesMovieIdPaymentRouteImport } from './routes/movies.$movieId_.payment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdSeatsRoute = MoviesMovieIdSeatsRouteImport.update({
  id: '/movies/$movieId_/seats',
  path: '/movies/$movieId/seats',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdPaymentRoute = MoviesMovieIdPaymentRouteImport.update({
  id: '/movies/$movieId_/payment',
  path: '/movies/$movieId/payment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/$movieId/payment': typeof MoviesMovieIdPaymentRoute
  '/movies/$movieId/seats': typeof MoviesMovieIdSeatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/$movieId/payment': typeof MoviesMovieIdPaymentRoute
  '/movies/$movieId/seats': typeof MoviesMovieIdSeatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/movies/$movieId_/payment': typeof MoviesMovieIdPaymentRoute
  '/movies/$movieId_/seats': typeof MoviesMovieIdSeatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/movies/$movieId'
    | '/movies/$movieId/payment'
    | '/movies/$movieId/seats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/movies/$movieId'
    | '/movies/$movieId/payment'
    | '/movies/$movieId/seats'
  id:
    | '__root__'
    | '/'
    | '/movies/$movieId'
    | '/movies/$movieId_/payment'
    | '/movies/$movieId_/seats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  MoviesMovieIdPaymentRoute: typeof MoviesMovieIdPaymentRoute
  MoviesMovieIdSeatsRoute: typeof MoviesMovieIdSeatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId_/seats': {
      id: '/movies/$movieId_/seats'
      path: '/movies/$movieId/seats'
      fullPath: '/movies/$movieId/seats'
      preLoaderRoute: typeof MoviesMovieIdSeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId_/payment': {
      id: '/movies/$movieId_/payment'
      path: '/movies/$movieId/payment'
      fullPath: '/movies/$movieId/payment'
      preLoaderRoute: typeof MoviesMovieIdPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  MoviesMovieIdPaymentRoute: MoviesMovieIdPaymentRoute,
  MoviesMovieIdSeatsRoute: MoviesMovieIdSeatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
