/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesMovieIdRouteImport } from './routes/movies.$movieId'
import { Route as MoviesMovieIdSeatsRouteImport } from './routes/movies.$movieId.seats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdSeatsRoute = MoviesMovieIdSeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => MoviesMovieIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movies/$movieId': typeof MoviesMovieIdRouteWithChildren
  '/movies/$movieId/seats': typeof MoviesMovieIdSeatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movies/$movieId': typeof MoviesMovieIdRouteWithChildren
  '/movies/$movieId/seats': typeof MoviesMovieIdSeatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movies/$movieId': typeof MoviesMovieIdRouteWithChildren
  '/movies/$movieId/seats': typeof MoviesMovieIdSeatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movies/$movieId' | '/movies/$movieId/seats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movies/$movieId' | '/movies/$movieId/seats'
  id: '__root__' | '/' | '/movies/$movieId' | '/movies/$movieId/seats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId/seats': {
      id: '/movies/$movieId/seats'
      path: '/seats'
      fullPath: '/movies/$movieId/seats'
      preLoaderRoute: typeof MoviesMovieIdSeatsRouteImport
      parentRoute: typeof MoviesMovieIdRoute
    }
  }
}

interface MoviesMovieIdRouteChildren {
  MoviesMovieIdSeatsRoute: typeof MoviesMovieIdSeatsRoute
}

const MoviesMovieIdRouteChildren: MoviesMovieIdRouteChildren = {
  MoviesMovieIdSeatsRoute: MoviesMovieIdSeatsRoute,
}

const MoviesMovieIdRouteWithChildren = MoviesMovieIdRoute._addFileChildren(
  MoviesMovieIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoviesMovieIdRoute: MoviesMovieIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
